# Generated by Django 4.2.3 on 2023-11-07 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='branch',
            new_name='brand',
        ),
    ]
