
# Generated by Django 4.2.3 on 2023-11-13 10:13


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_rentalpost_image_desc1_rentalpost_image_desc2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalpost',
            options={'verbose_name': 'Quản lí request'},
        ),
    ]
