# Generated by Django 4.2.3 on 2023-11-07 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_bookingpost_created_at_delete_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingpost',
            name='bidders',
        ),
    ]
