# Generated by Django 4.2.3 on 2023-11-07 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_bookingpost_image_desc2_bookingpost_image_desc3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingpost',
            name='image_desc1',
        ),
        migrations.RemoveField(
            model_name='bookingpost',
            name='image_desc2',
        ),
        migrations.RemoveField(
            model_name='bookingpost',
            name='image_desc3',
        ),
        migrations.RemoveField(
            model_name='bookingpost',
            name='image_desc4',
        ),
        migrations.RemoveField(
            model_name='bookingpost',
            name='image_desc5',
        ),
    ]
