# Generated by Django 4.2.3 on 2023-11-09 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0005_alter_cities_image_url_alter_vehicle_image_url'),
        ('rental', '0003_rentalpost_image_desc1_rentalpost_image_desc2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField()),
                ('service', models.CharField(choices=[('bidding', 'Đấu giá chuyến xe')], default='bidding', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.brand')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.vehicle')),
            ],
        ),
    ]
