# Generated by Django 4.2.3 on 2023-11-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0003_rename_post_id_proposal_bookingpost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('waiting', 'Đợi phản hồi'), ('successful', 'Thành công'), ('failed', 'Thất bại')], default='waiting', max_length=20),
        ),
    ]
