# Generated by Django 4.2.3 on 2023-11-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0004_proposal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='license_plate',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
