# Generated by Django 4.2.3 on 2023-11-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0006_rename_bookingpost_proposal_booking_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('waiting', 'Chờ xác nhận'), ('successful', 'Thành công'), ('failed', 'Thất bại')], default='waiting', max_length=20),
        ),
    ]
