# Generated by Django 4.2.3 on 2023-11-06 15:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50)),
                ('image_url', models.ImageField(default='user_media/images/doc_id/Untitled_HFTEcCo.png', upload_to='user_media/images/doc_id')),
                ('index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50)),
                ('image_url', models.ImageField(default='media/user_media/images/doc_id/Untitled_HFTEcCo.png', upload_to='media/user_media/images/doc_id')),
                ('index', models.IntegerField()),
            ],
        ),
    ]
