# Generated by Django 4.2.3 on 2023-11-06 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_remove_cities_index_remove_vehicle_index_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities',
            old_name='order',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='order',
            new_name='position',
        ),
    ]
