# Generated by Django 4.2.3 on 2023-11-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_rename_order_cities_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='division_type',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cities',
            name='image_url',
            field=models.ImageField(upload_to='assets/car_type'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image_url',
            field=models.ImageField(upload_to='assets/location'),
        ),
    ]
