# Generated by Django 4.2.3 on 2023-11-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_cities_division_type_alter_cities_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='image_url',
            field=models.ImageField(upload_to='assets/location'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image_url',
            field=models.ImageField(upload_to='assets/car_type'),
        ),
    ]
