# Generated by Django 4.2.3 on 2023-10-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_is_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='back_id_image',
            field=models.ImageField(default='user_media/images/default_front_id_image.jpg', upload_to='user_media/images/doc_id/'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_expired',
            field=models.DateField(default='2001-01-01'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_issued',
            field=models.DateField(default='2001-01-01'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default='2001-01-01'),
        ),
        migrations.AddField(
            model_name='user',
            name='doc_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='front_id_image',
            field=models.ImageField(default='user_media/images/default_front_id_image.jpg', upload_to='user_media/images/doc_id/'),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Nam'), ('Female', 'Nữ'), ('Unknown', 'Không xác định')], default='Unknown', max_length=7),
        ),
        migrations.AddField(
            model_name='user',
            name='hometown',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='place_issued',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
