# Generated by Django 4.2.3 on 2023-11-07 15:03

from django.db import migrations, models
import functools
import ultis.helper


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_user_date_expired_alter_user_date_issued_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='back_id_image',
            field=models.ImageField(default='/', upload_to=functools.partial(ultis.helper.custom_user_image_path, *(), **{'path': 'docid'})),
        ),
        migrations.AlterField(
            model_name='user',
            name='front_id_image',
            field=models.ImageField(default='/', upload_to=functools.partial(ultis.helper.custom_user_image_path, *(), **{'path': 'docid'})),
        ),
    ]
