# Generated by Django 4.2.3 on 2023-11-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_otp_id_alter_userreview_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='log',
            field=models.TextField(blank=True),
        ),
    ]
