# Generated by Django 4.2.3 on 2023-11-13 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_user_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Quản lí User'},
        ),
    ]
